/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton; // Sẽ dùng để tạo nút món ăn động
import javax.swing.JOptionPane; // Để hiển thị thông báo
import javax.swing.table.DefaultTableModel; // Để quản lý dữ liệu bảng





/**
 *
 * @author homes
 */
public class FormOder extends javax.swing.JFrame {
    private DefaultTableModel hoaDonTableModel; // Biến để quản lý dữ liệu bảng hóa đơn
    private double tongTien = 0.0; // Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
// Biến để lưu tổng tiền
    // ... Các khai báo biến khác mà NetBeans tự tạo (JTable, JLabel cho tổng tiền, v.v.)
    // Đảm bảo bạn đã đặt tên biến cho JTable là tblHoaDon và JLabel tổng tiền là lblTongTien (hoặc tên tương tự)
    


 

    // ... Các phương thức khác sẽ được viết ở đây ...

    /**
     * Creates new form FormOder
     */
    public FormOder() {
       
        initComponents();
        initHoaDonTable(); // Gọi phương thức khởi tạo bảng hóa đơn
    // Tùy chọn: Đặt cửa sổ ở giữa màn hình khi khởi động
    setLocationRelativeTo(null);
    // Tùy chọn: Đặt tiêu đề cho cửa sổ
    setTitle("Hệ thống quản lý quán Cafe");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblTongTien = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panelMenuLoai = new javax.swing.JPanel();
        menuToolBar = new javax.swing.JToolBar();
        btnCafe = new javax.swing.JButton();
        btnNuocTraiCay = new javax.swing.JButton();
        btnBanhNgot = new javax.swing.JButton();
        menuScrollPane = new javax.swing.JScrollPane();
        cardPanelForMenuItems = new javax.swing.JPanel();
        pnlCafeContent = new javax.swing.JPanel();
        pnlEspresso = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblAnhCappuccino = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlCappuccino = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblAnhEspresso1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlMocha = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblAnhMocha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlBacxiu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblAnhBacxiu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlCaramel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblAnhCaramel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlDenda = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblAnhDenda = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlNuocTraiCayContent = new javax.swing.JPanel();
        pnlEspresso1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblAnhTao = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlCappuccino1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblAnhBuoi = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlMocha1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblAnhOi = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlBacxiu1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblAnhCam = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnlCaramel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblAnhDau = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pnlDenda1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lblAnhBo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pnlBanhContent = new javax.swing.JPanel();
        pnlEspresso2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lblAnhBonglan = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnlCappuccino2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        lblAnhSukem = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pnlMocha2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lblAnhDonut = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pnlBacxiu2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lblAnhKem = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        pnlCaramel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        lblAnhChocopie = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        pnlDenda2 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        lblAnhMuffin = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("#9Slide03 Montserrat Alternates", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("CÁC MÓN BẠN CHỌN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -10, 170, 70));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 60));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên món", "Số lượng", "Giá", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 430, 250));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        lblTongTien.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 153, 0));
        lblTongTien.setText("TỔNG TIỀN: 0 VND");
        jPanel4.add(lblTongTien);

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 255));
        jButton4.setText("Xong");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 0));

        jLabel3.setFont(new java.awt.Font("SG85-CHI SON 2", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("MỜI QUÝ KHÁCH CHỌN MÓN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelMenuLoai.setBackground(new java.awt.Color(153, 153, 153));
        panelMenuLoai.setLayout(new java.awt.BorderLayout());

        menuToolBar.setBackground(new java.awt.Color(153, 255, 255));
        menuToolBar.setRollover(true);

        btnCafe.setBackground(new java.awt.Color(102, 102, 0));
        btnCafe.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCafe.setForeground(new java.awt.Color(255, 153, 51));
        btnCafe.setText("Cafe");
        btnCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCafe.setPreferredSize(new java.awt.Dimension(100, 50));
        btnCafe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeActionPerformed(evt);
            }
        });
        menuToolBar.add(btnCafe);

        btnNuocTraiCay.setBackground(new java.awt.Color(102, 102, 0));
        btnNuocTraiCay.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnNuocTraiCay.setForeground(new java.awt.Color(255, 153, 51));
        btnNuocTraiCay.setText("Nước trái cây");
        btnNuocTraiCay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuocTraiCay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuocTraiCay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuocTraiCayActionPerformed(evt);
            }
        });
        menuToolBar.add(btnNuocTraiCay);

        btnBanhNgot.setBackground(new java.awt.Color(102, 102, 0));
        btnBanhNgot.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBanhNgot.setForeground(new java.awt.Color(255, 153, 0));
        btnBanhNgot.setText("Bánh ngọt");
        btnBanhNgot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBanhNgot.setPreferredSize(new java.awt.Dimension(100, 50));
        btnBanhNgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanhNgotActionPerformed(evt);
            }
        });
        menuToolBar.add(btnBanhNgot);

        panelMenuLoai.add(menuToolBar, java.awt.BorderLayout.PAGE_START);

        menuScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        menuScrollPane.setViewportView(cardPanelForMenuItems);

        cardPanelForMenuItems.setBackground(new java.awt.Color(153, 255, 204));
        cardPanelForMenuItems.setLayout(new java.awt.CardLayout());

        pnlCafeContent.setBackground(new java.awt.Color(102, 51, 0));
        pnlCafeContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEspresso.setBorder(new javax.swing.border.MatteBorder(null));
        pnlEspresso.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Cappuccino");
        pnlEspresso.add(jLabel4);

        lblAnhCappuccino.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\Cappuccinof.jpg")); // NOI18N
        lblAnhCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhCappuccinoMouseClicked(evt);
            }
        });
        pnlEspresso.add(lblAnhCappuccino);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("50.000");
        pnlEspresso.add(jLabel5);

        pnlCafeContent.add(pnlEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 100, 130));

        pnlCappuccino.setBorder(new javax.swing.border.MatteBorder(null));
        pnlCappuccino.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("Espresso");
        pnlCappuccino.add(jLabel6);

        lblAnhEspresso1.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\Espressof.jpg")); // NOI18N
        lblAnhEspresso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhEspresso1MouseClicked(evt);
            }
        });
        pnlCappuccino.add(lblAnhEspresso1);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 0));
        jLabel7.setText("45.000");
        pnlCappuccino.add(jLabel7);

        pnlCafeContent.add(pnlCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 130));

        pnlMocha.setBorder(new javax.swing.border.MatteBorder(null));
        pnlMocha.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 0));
        jLabel8.setText("Mocha");
        pnlMocha.add(jLabel8);

        lblAnhMocha.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\Espressof.jpg")); // NOI18N
        lblAnhMocha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMochaMouseClicked(evt);
            }
        });
        pnlMocha.add(lblAnhMocha);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 0));
        jLabel9.setText("55.000");
        pnlMocha.add(jLabel9);

        pnlCafeContent.add(pnlMocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 100, 130));

        pnlBacxiu.setBorder(new javax.swing.border.MatteBorder(null));
        pnlBacxiu.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 0));
        jLabel10.setText("Bạc xỉu");
        pnlBacxiu.add(jLabel10);

        lblAnhBacxiu.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\bacxiuf.jpg")); // NOI18N
        lblAnhBacxiu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhBacxiuMouseClicked(evt);
            }
        });
        pnlBacxiu.add(lblAnhBacxiu);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 0));
        jLabel11.setText("50.000");
        pnlBacxiu.add(jLabel11);

        pnlCafeContent.add(pnlBacxiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 130));

        pnlCaramel.setBorder(new javax.swing.border.MatteBorder(null));
        pnlCaramel.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 0));
        jLabel12.setText("Caramel");
        pnlCaramel.add(jLabel12);

        lblAnhCaramel.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\Caramelf.jpg")); // NOI18N
        lblAnhCaramel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhCaramelMouseClicked(evt);
            }
        });
        pnlCaramel.add(lblAnhCaramel);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 0));
        jLabel13.setText("55.000");
        pnlCaramel.add(jLabel13);

        pnlCafeContent.add(pnlCaramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 130));

        pnlDenda.setBorder(new javax.swing.border.MatteBorder(null));
        pnlDenda.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 0));
        jLabel14.setText("Đen đá");
        pnlDenda.add(jLabel14);

        lblAnhDenda.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\denf.jpg")); // NOI18N
        lblAnhDenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhDendaMouseClicked(evt);
            }
        });
        pnlDenda.add(lblAnhDenda);

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 0));
        jLabel15.setText("55.000");
        pnlDenda.add(jLabel15);

        pnlCafeContent.add(pnlDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, 130));

        cardPanelForMenuItems.add(pnlCafeContent, "cafe");

        pnlNuocTraiCayContent.setBackground(new java.awt.Color(204, 255, 255));
        pnlNuocTraiCayContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEspresso1.setBorder(new javax.swing.border.MatteBorder(null));
        pnlEspresso1.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 0));
        jLabel16.setText("Nước ép táo");
        pnlEspresso1.add(jLabel16);

        lblAnhTao.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\tao.jpg")); // NOI18N
        lblAnhTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhTaoMouseClicked(evt);
            }
        });
        pnlEspresso1.add(lblAnhTao);

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 0));
        jLabel17.setText("40.000");
        pnlEspresso1.add(jLabel17);

        pnlNuocTraiCayContent.add(pnlEspresso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 100, 130));

        pnlCappuccino1.setBorder(new javax.swing.border.MatteBorder(null));
        pnlCappuccino1.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 0));
        jLabel18.setText("Nước ép bưởi");
        pnlCappuccino1.add(jLabel18);

        lblAnhBuoi.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\buoi.jpg")); // NOI18N
        lblAnhBuoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhBuoiMouseClicked(evt);
            }
        });
        pnlCappuccino1.add(lblAnhBuoi);

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 0));
        jLabel19.setText("40.000");
        pnlCappuccino1.add(jLabel19);

        pnlNuocTraiCayContent.add(pnlCappuccino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 130));

        pnlMocha1.setBorder(new javax.swing.border.MatteBorder(null));
        pnlMocha1.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 0));
        jLabel20.setText("Nước ép ổi");
        pnlMocha1.add(jLabel20);

        lblAnhOi.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\oi.jpg")); // NOI18N
        lblAnhOi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhOiMouseClicked(evt);
            }
        });
        pnlMocha1.add(lblAnhOi);

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 0));
        jLabel21.setText("40.000");
        pnlMocha1.add(jLabel21);

        pnlNuocTraiCayContent.add(pnlMocha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 130));

        pnlBacxiu1.setBorder(new javax.swing.border.MatteBorder(null));
        pnlBacxiu1.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 0));
        jLabel22.setText("Nước cam");
        pnlBacxiu1.add(jLabel22);

        lblAnhCam.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\cam.jpg")); // NOI18N
        lblAnhCam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhCamMouseClicked(evt);
            }
        });
        pnlBacxiu1.add(lblAnhCam);

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 0));
        jLabel23.setText("40.000");
        pnlBacxiu1.add(jLabel23);

        pnlNuocTraiCayContent.add(pnlBacxiu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 100, 130));

        pnlCaramel1.setBorder(new javax.swing.border.MatteBorder(null));
        pnlCaramel1.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 0));
        jLabel24.setText("Sinh tố dâu");
        pnlCaramel1.add(jLabel24);

        lblAnhDau.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\dau.jpg")); // NOI18N
        lblAnhDau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhDauMouseClicked(evt);
            }
        });
        pnlCaramel1.add(lblAnhDau);

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 0));
        jLabel25.setText("50.000");
        pnlCaramel1.add(jLabel25);

        pnlNuocTraiCayContent.add(pnlCaramel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 130));

        pnlDenda1.setBorder(new javax.swing.border.MatteBorder(null));
        pnlDenda1.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 0));
        jLabel26.setText("Sinh tố bơ");
        pnlDenda1.add(jLabel26);

        lblAnhBo.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\bo.jpg")); // NOI18N
        lblAnhBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhBoMouseClicked(evt);
            }
        });
        pnlDenda1.add(lblAnhBo);

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 0));
        jLabel27.setText("50.000");
        pnlDenda1.add(jLabel27);

        pnlNuocTraiCayContent.add(pnlDenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 130));

        cardPanelForMenuItems.add(pnlNuocTraiCayContent, "nuocTraiCay");

        pnlBanhContent.setBackground(new java.awt.Color(255, 153, 51));
        pnlBanhContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEspresso2.setBorder(new javax.swing.border.MatteBorder(null));
        pnlEspresso2.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 0));
        jLabel28.setText("Bông lan");
        pnlEspresso2.add(jLabel28);

        lblAnhBonglan.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\bonglan.jpg")); // NOI18N
        lblAnhBonglan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhBonglanMouseClicked(evt);
            }
        });
        pnlEspresso2.add(lblAnhBonglan);

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 0));
        jLabel29.setText("40.000");
        pnlEspresso2.add(jLabel29);

        pnlBanhContent.add(pnlEspresso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 100, 130));

        pnlCappuccino2.setBorder(new javax.swing.border.MatteBorder(null));
        pnlCappuccino2.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 0));
        jLabel30.setText("Su kem");
        pnlCappuccino2.add(jLabel30);

        lblAnhSukem.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\bnh su kem.jpg")); // NOI18N
        lblAnhSukem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhSukemMouseClicked(evt);
            }
        });
        pnlCappuccino2.add(lblAnhSukem);

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 0));
        jLabel31.setText("40.000");
        pnlCappuccino2.add(jLabel31);

        pnlBanhContent.add(pnlCappuccino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 130));

        pnlMocha2.setBorder(new javax.swing.border.MatteBorder(null));
        pnlMocha2.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel32.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 0));
        jLabel32.setText("Donut");
        pnlMocha2.add(jLabel32);

        lblAnhDonut.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\donut.jpg")); // NOI18N
        lblAnhDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhDonutMouseClicked(evt);
            }
        });
        pnlMocha2.add(lblAnhDonut);

        jLabel33.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 0));
        jLabel33.setText("40.000");
        pnlMocha2.add(jLabel33);

        pnlBanhContent.add(pnlMocha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 130));

        pnlBacxiu2.setBorder(new javax.swing.border.MatteBorder(null));
        pnlBacxiu2.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel34.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 0));
        jLabel34.setText("Kem matcha");
        pnlBacxiu2.add(jLabel34);

        lblAnhKem.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\kem.jpg")); // NOI18N
        lblAnhKem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhKemMouseClicked(evt);
            }
        });
        pnlBacxiu2.add(lblAnhKem);

        jLabel35.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 0));
        jLabel35.setText("40.000");
        pnlBacxiu2.add(jLabel35);

        pnlBanhContent.add(pnlBacxiu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 100, 130));

        pnlCaramel2.setBorder(new javax.swing.border.MatteBorder(null));
        pnlCaramel2.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel36.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 0));
        jLabel36.setText("Chocopie");
        pnlCaramel2.add(jLabel36);

        lblAnhChocopie.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\choco.jpg")); // NOI18N
        lblAnhChocopie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhChocopieMouseClicked(evt);
            }
        });
        pnlCaramel2.add(lblAnhChocopie);

        jLabel37.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 0));
        jLabel37.setText("50.000");
        pnlCaramel2.add(jLabel37);

        pnlBanhContent.add(pnlCaramel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 130));

        pnlDenda2.setBorder(new javax.swing.border.MatteBorder(null));
        pnlDenda2.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 0));
        jLabel38.setText("Muffin");
        pnlDenda2.add(jLabel38);

        lblAnhMuffin.setIcon(new javax.swing.ImageIcon("D:\\fe javaBTLL\\muffin.jpg")); // NOI18N
        lblAnhMuffin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMuffinMouseClicked(evt);
            }
        });
        pnlDenda2.add(lblAnhMuffin);

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 0));
        jLabel39.setText("50.000");
        pnlDenda2.add(jLabel39);

        pnlBanhContent.add(pnlDenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 130));

        cardPanelForMenuItems.add(pnlBanhContent, "banhNgot");

        menuScrollPane.setViewportView(cardPanelForMenuItems);

        panelMenuLoai.add(menuScrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelMenuLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenuLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lblAnhEspresso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhEspresso1MouseClicked
        // TODO add your handling code here:
        MonAn espresso = new MonAn("Espresso", 45000.0); // Tạo đối tượng MonAn với tên và giá chính xác
    themMonVaoHoaDon(espresso); // Gọi phương thức để thêm vào hóa đơn
    }//GEN-LAST:event_lblAnhEspresso1MouseClicked

    private void lblAnhBuoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhBuoiMouseClicked
        // TODO add your handling code here:
         MonAn nuocepbuoi = new MonAn("Nước ép bưởi", 40000.0); // Tên và giá chính xác
    themMonVaoHoaDon(nuocepbuoi);
    }//GEN-LAST:event_lblAnhBuoiMouseClicked

    private void lblAnhSukemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhSukemMouseClicked
        // TODO add your handling code here:
        MonAn sukem = new MonAn("Su kem", 40000.0);
        themMonVaoHoaDon(sukem);
    }//GEN-LAST:event_lblAnhSukemMouseClicked

    private void lblAnhCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhCappuccinoMouseClicked
        // TODO add your handling code here:
         MonAn cappuccino = new MonAn("Cappuccino", 50000.0); // Tên và giá chính xác
    themMonVaoHoaDon(cappuccino);
    }//GEN-LAST:event_lblAnhCappuccinoMouseClicked

    private void lblAnhMochaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMochaMouseClicked
        // TODO add your handling code here:
         MonAn mocha = new MonAn("Mocha", 55000.0); // Tên và giá chính xác
    themMonVaoHoaDon(mocha);
    }//GEN-LAST:event_lblAnhMochaMouseClicked

    private void lblAnhBacxiuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhBacxiuMouseClicked
        // TODO add your handling code here:
         MonAn bacxiu = new MonAn("Bạc xỉu", 50000.0); // Tên và giá chính xác
    themMonVaoHoaDon(bacxiu);
    }//GEN-LAST:event_lblAnhBacxiuMouseClicked

    private void lblAnhDendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhDendaMouseClicked
        // TODO add your handling code here:
         MonAn denda = new MonAn("Đen đá", 55000.0); // Tên và giá chính xác
    themMonVaoHoaDon(denda);
    }//GEN-LAST:event_lblAnhDendaMouseClicked

    private void lblAnhCaramelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhCaramelMouseClicked
        // TODO add your handling code here:
         MonAn caramel = new MonAn("Caramel", 55000.0); // Tên và giá chính xác
    themMonVaoHoaDon(caramel);
    }//GEN-LAST:event_lblAnhCaramelMouseClicked

    private void lblAnhTaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhTaoMouseClicked
        // TODO add your handling code here:
        MonAn nuoceptao = new MonAn ("Nước ép táo", 40000.0);
        themMonVaoHoaDon(nuoceptao);
    }//GEN-LAST:event_lblAnhTaoMouseClicked

    private void lblAnhOiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhOiMouseClicked
        // TODO add your handling code here:
        MonAn nuocepoi = new MonAn("Nước ép ổi", 40000.0);
        themMonVaoHoaDon(nuocepoi);
    }//GEN-LAST:event_lblAnhOiMouseClicked

    private void lblAnhCamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhCamMouseClicked
        // TODO add your handling code here:
        MonAn nuoccam = new MonAn("Nước cam", 40000.0);
        themMonVaoHoaDon(nuoccam);
    }//GEN-LAST:event_lblAnhCamMouseClicked

    private void lblAnhBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhBoMouseClicked
        // TODO add your handling code here:
        MonAn stbo = new MonAn("Sinh tố bơ", 50000.0);
        themMonVaoHoaDon(stbo);
    }//GEN-LAST:event_lblAnhBoMouseClicked

    private void lblAnhDauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhDauMouseClicked
        // TODO add your handling code here:
        MonAn stdau = new MonAn("Sinh tố dâu", 50000.0);
        themMonVaoHoaDon(stdau);
    }//GEN-LAST:event_lblAnhDauMouseClicked

    private void lblAnhBonglanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhBonglanMouseClicked
        // TODO add your handling code here:
        MonAn bonglan = new MonAn("Bông lan", 40000.0);
        themMonVaoHoaDon(bonglan);
    }//GEN-LAST:event_lblAnhBonglanMouseClicked

    private void lblAnhDonutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhDonutMouseClicked
        // TODO add your handling code here:
        MonAn donut = new MonAn("Donut", 40000.0);
        themMonVaoHoaDon(donut);
    }//GEN-LAST:event_lblAnhDonutMouseClicked

    private void lblAnhKemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhKemMouseClicked
        // TODO add your handling code here:
        MonAn kemmatcha = new MonAn("Kem matcha", 40000.0);
        themMonVaoHoaDon(kemmatcha);
    }//GEN-LAST:event_lblAnhKemMouseClicked

    private void lblAnhMuffinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMuffinMouseClicked
        // TODO add your handling code here:
        MonAn muffin = new MonAn("Muffin", 50000.0);
        themMonVaoHoaDon(muffin);
    }//GEN-LAST:event_lblAnhMuffinMouseClicked

    private void lblAnhChocopieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhChocopieMouseClicked
        // TODO add your handling code here:
        MonAn chocopie = new MonAn("Chocopie", 50000.0);
        themMonVaoHoaDon(chocopie);
    }//GEN-LAST:event_lblAnhChocopieMouseClicked

    private void btnBanhNgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanhNgotActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) cardPanelForMenuItems.getLayout();
        cl.show(cardPanelForMenuItems, "banhNgot");
        menuScrollPane.getVerticalScrollBar().setValue(0); // Cuộn về đầu
    }//GEN-LAST:event_btnBanhNgotActionPerformed

    private void btnNuocTraiCayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuocTraiCayActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) cardPanelForMenuItems.getLayout();
        cl.show(cardPanelForMenuItems, "nuocTraiCay");
        menuScrollPane.getVerticalScrollBar().setValue(0); // Cuộn về đầu
    }//GEN-LAST:event_btnNuocTraiCayActionPerformed

    private void btnCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeActionPerformed
        // TODO add your handling code here:
        // Lấy CardLayout từ panel chứa các card
        CardLayout cl = (CardLayout) cardPanelForMenuItems.getLayout();
        // Hiển thị card có tên "cafe"
        cl.show(cardPanelForMenuItems, "cafe");

        // Tùy chọn: Cuộn JScrollPane về đầu khi chuyển card
        // Điều này đảm bảo người dùng luôn thấy đầu danh sách món khi chuyển menu
        menuScrollPane.getVerticalScrollBar().setValue(0);
    }//GEN-LAST:event_btnCafeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanhNgot;
    private javax.swing.JButton btnCafe;
    private javax.swing.JButton btnNuocTraiCay;
    private javax.swing.JPanel cardPanelForMenuItems;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhBacxiu;
    private javax.swing.JLabel lblAnhBo;
    private javax.swing.JLabel lblAnhBonglan;
    private javax.swing.JLabel lblAnhBuoi;
    private javax.swing.JLabel lblAnhCam;
    private javax.swing.JLabel lblAnhCappuccino;
    private javax.swing.JLabel lblAnhCaramel;
    private javax.swing.JLabel lblAnhChocopie;
    private javax.swing.JLabel lblAnhDau;
    private javax.swing.JLabel lblAnhDenda;
    private javax.swing.JLabel lblAnhDonut;
    private javax.swing.JLabel lblAnhEspresso1;
    private javax.swing.JLabel lblAnhKem;
    private javax.swing.JLabel lblAnhMocha;
    private javax.swing.JLabel lblAnhMuffin;
    private javax.swing.JLabel lblAnhOi;
    private javax.swing.JLabel lblAnhSukem;
    private javax.swing.JLabel lblAnhTao;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JToolBar menuToolBar;
    private javax.swing.JPanel panelMenuLoai;
    private javax.swing.JPanel pnlBacxiu;
    private javax.swing.JPanel pnlBacxiu1;
    private javax.swing.JPanel pnlBacxiu2;
    private javax.swing.JPanel pnlBanhContent;
    private javax.swing.JPanel pnlCafeContent;
    private javax.swing.JPanel pnlCappuccino;
    private javax.swing.JPanel pnlCappuccino1;
    private javax.swing.JPanel pnlCappuccino2;
    private javax.swing.JPanel pnlCaramel;
    private javax.swing.JPanel pnlCaramel1;
    private javax.swing.JPanel pnlCaramel2;
    private javax.swing.JPanel pnlDenda;
    private javax.swing.JPanel pnlDenda1;
    private javax.swing.JPanel pnlDenda2;
    private javax.swing.JPanel pnlEspresso;
    private javax.swing.JPanel pnlEspresso1;
    private javax.swing.JPanel pnlEspresso2;
    private javax.swing.JPanel pnlMocha;
    private javax.swing.JPanel pnlMocha1;
    private javax.swing.JPanel pnlMocha2;
    private javax.swing.JPanel pnlNuocTraiCayContent;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables

    private void initHoaDonTable() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       String[] columnNames = {"Tên món", "Số lượng", "Giá / SP", "Thành tiền", "Xóa"};
    hoaDonTableModel = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Cho phép sửa cột "Số lượng" (index 1) và cột "Xóa" (index 4)
            return column == 1 || column == 4;
        }
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (columnIndex == 4) return String.class; // Hoặc JButton.class nếu bạn dùng renderer/editor phức tạp hơn
            if (columnIndex == 1) return Integer.class;
            if (columnIndex == 2 || columnIndex == 3) return Double.class;
            return String.class;
        }
    };
    tblHoaDon.setModel(hoaDonTableModel); // Đặt model cho JTable của bạn (đảm bảo tên biến là tblHoaDon)

    // Tùy chỉnh chiều rộng cột (tùy chọn)
    tblHoaDon.getColumnModel().getColumn(0).setPreferredWidth(150); // Tên món
    tblHoaDon.getColumnModel().getColumn(1).setPreferredWidth(60);  // Số lượng
    tblHoaDon.getColumnModel().getColumn(2).setPreferredWidth(80);  // Giá
    tblHoaDon.getColumnModel().getColumn(3).setPreferredWidth(100); // Thành tiền
    tblHoaDon.getColumnModel().getColumn(4).setPreferredWidth(50);  // Xóa

    // Bắt sự kiện click vào cột "Xóa" trong bảng (nếu bạn muốn có chữ "Xóa" và click vào đó)
    tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int column = tblHoaDon.columnAtPoint(evt.getPoint());
            int row = tblHoaDon.rowAtPoint(evt.getPoint());
            if (column == 4 && row >= 0) { // Nếu click vào cột "Xóa" (index 4)
                xoaMonKhoiHoaDon(row);
            }
        }

           private void xoaMonKhoiHoaDon(int row) {
               throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
           }
    });

    // Bắt sự kiện chỉnh sửa số lượng trong bảng
    tblHoaDon.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
        @Override
        public void tableChanged(javax.swing.event.TableModelEvent e) {
            if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                int row = e.getFirstRow();
                int column = e.getColumn();
                if (column == 1) { // Nếu cột số lượng được chỉnh sửa
                    capNhatSoLuongMon(row);
                }
            }
        }

    });
    }
    
    
   
    
    private void themMonVaoHoaDon(MonAn mon) {
        boolean found = false;
        // Duyệt qua các hàng hiện có trong bảng hóa đơn
        for (int i = 0; i < hoaDonTableModel.getRowCount(); i++) {
            String tenMonTrongBang = (String) hoaDonTableModel.getValueAt(i, 0);
            if (tenMonTrongBang.equals(mon.getTenMon())) {
                // Món đã có trong hóa đơn, chỉ cần tăng số lượng
                int currentSoLuong = (Integer) hoaDonTableModel.getValueAt(i, 1);
                int newSoLuong = currentSoLuong + 1;
                hoaDonTableModel.setValueAt(newSoLuong, i, 1);
                hoaDonTableModel.setValueAt(newSoLuong * mon.getGia(), i, 3); // Cập nhật Thành tiền
                found = true;
                break;
            }
        }

        if (!found) {
            // Món chưa có, thêm một hàng mới vào bảng
            Object[] rowData = {mon.getTenMon(), 1, mon.getGia(), 1 * mon.getGia(), "Xóa"};
            hoaDonTableModel.addRow(rowData);
        }
        capNhatTongTien(); // Cập nhật tổng tiền sau khi thêm/sửa món
    }

    private void capNhatTongTien() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        tongTien = 0.0;
    for (int i = 0; i < hoaDonTableModel.getRowCount(); i++) {
        tongTien += (Double) hoaDonTableModel.getValueAt(i, 3); // Cộng tổng cột "Thành tiền"
    }
    lblTongTien.setText("TỔNG TIỀN: " + String.format("%,.0f", tongTien) + " VND"); // Format tiền tệ, đảm bảo lblTongTien là tên biến của JLabel tổng tiền
    }
    private void xoaMonKhoiHoaDon(int row) {
              // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                if (row >= 0 && row < hoaDonTableModel.getRowCount()) {
        hoaDonTableModel.removeRow(row); // Xóa hàng khỏi bảng
        capNhatTongTien(); // Cập nhật tổng tiền
    }
           }
    private void capNhatSoLuongMon(int row) {
               //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
               if (row >= 0 && row < hoaDonTableModel.getRowCount()) {
        try {
            int newSoLuong = (Integer) hoaDonTableModel.getValueAt(row, 1); // Lấy số lượng mới
            if (newSoLuong <= 0) { // Nếu số lượng <= 0, xóa món
                 xoaMonKhoiHoaDon(row);
                 return; // Thoát để tránh lỗi index sau khi xóa
            }
            double giaSP = (Double) hoaDonTableModel.getValueAt(row, 2); // Lấy giá/SP
            hoaDonTableModel.setValueAt(newSoLuong * giaSP, row, 3); // Cập nhật cột Thành tiền
            capNhatTongTien(); // Cập nhật tổng tiền
        } catch (ClassCastException | NullPointerException ex) {
            System.err.println("Lỗi nhập số lượng: " + ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ! Vui lòng nhập số nguyên dương.", "Lỗi nhập liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
            // Có thể reset lại giá trị cũ nếu muốn, hoặc đơn giản là bỏ qua
            // hoaDonTableModel.fireTableRowsUpdated(row, row); // Buộc JTable cập nhật lại hàng đó
        }
    }
           }
    
}
